name: PR Build Check

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-latest
    name: Build & Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: '10.15.1'

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Frontend
        run: pnpm run build
        working-directory: ./frontend

      - name: Lint
        run: pnpm run lint